import PDFDocument from 'pdfkit';

export type AttendancePdfRow = {
  rollNo: number;
  admissionNo: string;
  name: string;
  status: 'PRESENT' | 'ABSENT' | 'LEAVE';
};

type AttendancePdfInput = {
  schoolClass: string;
  section: string;
  subject: string;
  date: Date;
  period: number;
  teacherName: string;
  rows: AttendancePdfRow[];
};

export function generateAttendancePdf(input: AttendancePdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margins: { top: 38, right: 40, bottom: 42, left: 40 }, bufferPages: true, info: { Title: `Attendance - ${input.schoolClass} ${input.section}`, Author: 'Dr. Lockmandas Public School' } });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on('error', reject);
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const pageWidth = doc.page.width;
    const contentWidth = pageWidth - 80;
    const navy = '#171065';
    const blue = '#244f9e';
    const gold = '#ffd400';
    const line = '#d9dfE8';
    const muted = '#59677a';
    const columns = [40, 80, 180, 470];
    const widths = [40, 100, 290, 85];
    const rowHeight = 21;

    const drawDocumentHeader = () => {
      doc.rect(0, 0, pageWidth, 12).fill(gold);
      doc.fillColor(navy).font('Helvetica-Bold').fontSize(16).text('DR. LOCKMANDAS PUBLIC SCHOOL', 40, 34, { align: 'center', width: contentWidth });
      doc.fillColor(muted).font('Helvetica').fontSize(8).text('ETAH, UTTAR PRADESH | ACADEMIC YEAR 2026-27', 40, 57, { align: 'center', width: contentWidth });
      doc.moveTo(40, 74).lineTo(pageWidth - 40, 74).lineWidth(2).strokeColor(navy).stroke();
      doc.fillColor(blue).font('Helvetica-Bold').fontSize(14).text('ATTENDANCE REGISTER', 40, 86, { align: 'center', width: contentWidth });
      doc.fillColor('#172033').font('Helvetica').fontSize(9);
      doc.text(`Class: ${input.schoolClass} - Section ${input.section}`, 40, 114);
      doc.text(`Date: ${input.date.toLocaleDateString('en-GB', { timeZone: 'UTC' })}`, 310, 114);
      doc.text(`Subject: ${input.subject}`, 40, 130);
      doc.text(`Period: ${input.period}`, 310, 130);
      doc.text(`Marked by: ${input.teacherName}`, 40, 146);
      doc.text(`Total students: ${input.rows.length}`, 310, 146);
      doc.y = 170;
    };

    const drawTableHeader = () => {
      const y = doc.y;
      doc.rect(40, y, contentWidth, 24).fill(navy);
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8);
      ['ROLL', 'ADM. NO.', 'STUDENT NAME', 'STATUS'].forEach((label, index) => {
        doc.text(label, columns[index] + 5, y + 8, { width: widths[index] - 10 });
      });
      doc.y = y + 24;
    };

    const addPage = (first = false) => {
      if (!first) doc.addPage();
      drawDocumentHeader();
      drawTableHeader();
    };

    const pages = Array.from({ length: Math.ceil(input.rows.length / 25) }, (_, pageIndex) => input.rows.slice(pageIndex * 25, pageIndex * 25 + 25));
    pages.forEach((pageRows, pageIndex) => {
      addPage(pageIndex === 0);
      pageRows.forEach((row, localIndex) => {
        const index = pageIndex * 25 + localIndex;
        const y = doc.y;
        doc.rect(40, y, contentWidth, rowHeight).fill(index % 2 ? '#f7f9fc' : '#ffffff');
        doc.moveTo(40, y + rowHeight).lineTo(pageWidth - 40, y + rowHeight).lineWidth(0.5).strokeColor(line).stroke();
        doc.fillColor('#1d2735').font('Helvetica').fontSize(8.5);
        doc.text(String(row.rollNo), columns[0] + 5, y + 6, { width: widths[0] - 10 });
        doc.text(row.admissionNo, columns[1] + 5, y + 6, { width: widths[1] - 10, ellipsis: true });
        doc.font('Helvetica-Bold').text(row.name, columns[2] + 5, y + 6, { width: widths[2] - 10, ellipsis: true });
        const statusColor = row.status === 'PRESENT' ? '#2f7d4f' : row.status === 'ABSENT' ? '#b42336' : '#a66b00';
        doc.fillColor(statusColor).font('Helvetica-Bold').text(row.status, columns[3] + 5, y + 6, { width: widths[3] - 10 });
        doc.y = y + rowHeight;
      });
    });

    const present = input.rows.filter((row) => row.status === 'PRESENT').length;
    const absent = input.rows.filter((row) => row.status === 'ABSENT').length;
    const leave = input.rows.filter((row) => row.status === 'LEAVE').length;
    doc.moveDown(0.7).fillColor(navy).font('Helvetica-Bold').fontSize(9).text(`SUMMARY   Present: ${present}   Absent: ${absent}   Leave: ${leave}`, 40, doc.y, { align: 'right', width: contentWidth });

    const range = doc.bufferedPageRange();
    for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
      doc.switchToPage(pageIndex);
      doc.page.margins.bottom = 0;
      doc.fillColor(muted).font('Helvetica').fontSize(7.5).text(`Generated by DLP School ERP | Page ${pageIndex + 1} of ${range.count}`, 40, doc.page.height - 24, { align: 'center', width: contentWidth, lineBreak: false });
    }
    doc.end();
  });
}
