import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import cookieParser from 'cookie-parser'; import path from 'node:path'; import { rateLimit } from 'express-rate-limit'; import { z } from 'zod'; import { env } from './config.js'; import { authRouter } from './routes/auth.js'; import { attendanceRouter } from './routes/attendance.js'; import { adminRouter } from './routes/admin.js'; import { portalRouter } from './routes/portal.js'; import { prisma } from './lib.js'; import { sendSchoolEnquiry } from './email.js';
const helmetMiddleware=(helmet as unknown as ()=>express.RequestHandler)();
const app=express(); app.set('trust proxy',1); app.disable('x-powered-by'); app.use(helmetMiddleware); app.use(cors({origin:env.WEB_URL,credentials:true})); app.use(express.json({limit:'8mb',type:'application/json'})); app.use(cookieParser());
const limit=(windowMs:number,max:number)=>rateLimit({windowMs,limit:max,standardHeaders:'draft-7',legacyHeaders:false,message:{message:'Too many requests. Please try again later.'}});
app.use('/api/auth/login',limit(15*60_000,10)); app.use('/api/auth/refresh',limit(15*60_000,60)); app.use('/api/auth/forgot-password',limit(60*60_000,5)); app.use('/api/auth/reset-password',limit(60*60_000,10)); app.use('/api/public',limit(15*60_000,120));
app.get('/api/health',(_q,r)=>r.json({status:'ok'})); app.use('/api/auth',authRouter); app.use('/api/attendance',attendanceRouter); app.use('/api/admin',adminRouter); app.use('/api/portal',portalRouter);
app.get('/api/public/highlights',async(_q,r,n)=>{try{const highlights=await prisma.homeHighlight.findMany({where:{active:true},orderBy:[{sortOrder:'asc'},{createdAt:'desc'}],select:{id:true,kind:true,eyebrow:true,title:true,description:true,actionLabel:true,actionUrl:true,fileName:true,fileSize:true,createdAt:true}});r.json(highlights.map((highlight)=>({...highlight,fileAvailable:Boolean(highlight.fileName)})))}catch(e){n(e)}});
app.get('/api/public/highlights/:id/file',async(q,r,n)=>{try{const highlight=await prisma.homeHighlight.findUnique({where:{id:q.params.id},select:{active:true,fileName:true,fileData:true}});if(!highlight?.active||!highlight.fileData)return r.status(404).json({message:'File not found'});const filename=(highlight.fileName||'school-update.pdf').replace(/[\\\"]/g,'');r.setHeader('Content-Type','application/pdf');r.setHeader('Content-Disposition',`inline; filename="${filename}"`);r.send(highlight.fileData)}catch(e){n(e)}});
const admissionSchema=z.object({studentName:z.string().trim().min(1).max(100),parentName:z.string().trim().min(1).max(100),email:z.string().trim().email().max(254),phone:z.string().trim().min(7).max(25),grade:z.string().trim().min(1).max(30),message:z.string().trim().max(2000).optional()}).strict();
const contactSchema=z.object({name:z.string().trim().min(1).max(100),email:z.string().trim().email().max(254),phone:z.string().trim().max(25).optional(),subject:z.string().trim().min(1).max(150),message:z.string().trim().max(2000)}).strict();
app.post('/api/public/admission',async(q,r,n)=>{try{const b=admissionSchema.parse(q.body);const enquiry=await prisma.admissionEnquiry.create({data:b});await sendSchoolEnquiry('Admission enquiry',b.email,{'Student name':b.studentName,'Parent / guardian':b.parentName,Email:b.email,Phone:b.phone,'Grade applying for':b.grade,Message:b.message});r.status(201).json(enquiry)}catch(e){n(e)}});
app.post('/api/public/contact',async(q,r,n)=>{try{const b=contactSchema.parse(q.body);const message=await prisma.contactMessage.create({data:b});await sendSchoolEnquiry('Contact message',b.email,{Name:b.name,Email:b.email,Phone:b.phone,Subject:b.subject,Message:b.message});r.status(201).json(message)}catch(e){n(e)}});
if(process.env.NODE_ENV==='production'&&!process.env.VERCEL){const web=path.resolve(process.cwd(),'..','web','dist');app.use(express.static(web));app.get('*',(_q,r)=>r.sendFile(path.join(web,'index.html')))}
app.use((e:any,_q:any,r:any,_n:any)=>{console.error(e);r.status(e.name==='ZodError'?400:500).json({message:e.name==='ZodError'?'Please check the submitted details':'Something went wrong',issues:e.issues})});
if(!process.env.VERCEL)app.listen(env.PORT,()=>console.log(`API ready on http://localhost:${env.PORT}`));
export default app;
