import { useEffect, useState } from 'react';
import { BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronRight, ClipboardCheck, Download, FileText, GraduationCap, LayoutDashboard, LogOut, Menu, Upload, Users, X } from 'lucide-react';
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
import { api } from '../api';
const items: any = { ADMIN: [[LayoutDashboard, 'Overview', ''], [Users, 'People', 'people'], [GraduationCap, 'Academics', 'academics'], [ClipboardCheck, 'Attendance reports', 'attendance'], [CalendarDays, 'Timetable', 'timetable'], [Bell, 'Notices', 'notices']], TEACHER: [[LayoutDashboard, 'Overview', ''], [ClipboardCheck, 'Mark attendance', 'attendance'], [FileText, 'Student TC', 'tc'], [BarChart3, 'Marks & results', 'marks'], [CalendarDays, 'Timetable', 'timetable'], [Bell, 'Class notices', 'notices']], STUDENT: [[LayoutDashboard, 'Overview', ''], [ClipboardCheck, 'My attendance', 'attendance'], [FileText, 'My TC', 'tc'], [BarChart3, 'My results', 'marks'], [CalendarDays, 'Timetable', 'timetable'], [Bell, 'Notices', 'notices']] };
export default function Portal() { const { user, logout } = useAuth(); const [open, setOpen] = useState(false); const nav = useNavigate(); return <div className="portal"><aside className={open ? 'open' : ''}><div className="portal-brand"><span className="crest"><BookOpen /></span><span><b>DLP School</b><small>ERP PORTAL</small></span><button onClick={() => setOpen(false)}><X /></button></div><nav>{items[user.role].map(([I, n, p]: any) => <button className={location.pathname === `/portal/${p}` || (p === '' && location.pathname === '/portal') ? 'active' : ''} onClick={() => { nav(`/portal/${p}`); setOpen(false); }}><I />{n}</button>)}</nav><div className="user-card"><div className="avatar">{user.name.split(' ').map((x: string) => x[0]).slice(0, 2)}</div><div><b>{user.name}</b><small>{user.role.toLowerCase()}</small></div><button onClick={async () => { await logout(); nav('/login'); }}><LogOut /></button></div></aside><section className="portal-main"><header><button className="menu" onClick={() => setOpen(true)}><Menu /></button><div><small>DR. LOCKMANDAS PUBLIC SCHOOL</small><b>Academic year 2026–27</b></div><span className="status-dot">● System online</span></header>
<Routes>

<Route index element={<Dashboard />}/>
<Route path="attendance" element={<Attendance />}/>
<Route path="tc" element={<TransferCertificate />}/>
<Route path="marks" element={<DataPage type="marks"/>}/>
<Route path="timetable" element={<DataPage type="timetable"/>}/>
<Route path="notices" element={<DataPage type="notices"/>}/>
<Route path="people" element={<AdminPeople />}/>
<Route path="academics" element={<Academics />}/>
<Route path="*" element={<Navigate to="/portal"/>}/></Routes></section></div>; }
function Dashboard() { const { user } = useAuth(); const [data, setData] = useState<any>(); useEffect(() => { api.get('/portal/dashboard').then(r => setData(r.data)); }, []); const greeting = new Date().getHours() < 12 ? 'Good morning' : 'Good afternoon'; return <div className="portal-content"><div className="page-title"><div><p>{greeting}, {user.name.split(' ')[0]}</p><h1>{user.role === 'ADMIN' ? 'School at a glance' : user.role === 'TEACHER' ? 'Your teaching day' : 'Your learning dashboard'}</h1></div><span>{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}</span></div>{user.role === 'ADMIN' ? <div className="metric-grid">{[['Students', data?.students, '+12 this month'], ['Teachers', data?.teachers, 'Active faculty'], ['Classes', data?.classes, 'Current year'], ['Approval requests', data?.pendingReopens, 'Attendance']].map(x => <article><span>{x[0]}</span><b>{x[1] ?? '—'}</b><small>{x[2]}</small></article>)}</div> : user.role === 'TEACHER' ? <><section className="welcome-card"><div><span>TODAY’S FOCUS</span><h2>Make every minute count.</h2><p>You have {data?.assignments?.length || 0} assigned class-subject groups.</p></div><ClipboardCheck /></section><h2 className="section-title">Assigned classes</h2><div className="class-grid">{data?.assignments?.map((a: any) => <article><span>{a.subject.code}</span><h3>{a.class.name} — {a.class.section}</h3><p>{a.subject.name}</p><ChevronRight /></article>)}</div></> : <section className="welcome-card"><div><span>WELCOME BACK</span><h2>{data?.student?.class?.name} — Section {data?.student?.class?.section}</h2><p>Roll number {data?.student?.rollNo} · Admission no. {data?.student?.admissionNo}</p></div><GraduationCap /></section>}<h2 className="section-title">School updates</h2><div className="empty-card"><Bell /><div><b>You’re all caught up</b><p>New circulars and reminders will appear here.</p></div></div></div>; }
function Attendance() { const { user } = useAuth(); if (user.role === 'TEACHER')
    return <TeacherAttendance />; if (user.role === 'STUDENT')
    return <StudentAttendance />; return <AdminAttendance />; }
function TeacherAttendance() { const [assign, setAssign] = useState<any[]>([]), [selected, setSelected] = useState(''), [date, setDate] = useState(new Date().toISOString().slice(0, 10)), [period, setPeriod] = useState(1), [reg, setReg] = useState<any>(), [statuses, setStatuses] = useState<Record<string, string>>({}), [msg, setMsg] = useState(''); useEffect(() => { api.get('/attendance/teacher/classes').then(r => { setAssign(r.data); if (r.data[0])
    setSelected(r.data[0].id); }); }, []); const a = assign.find(x => x.id === selected); const load = () => a && api.get('/attendance/register', { params: { classId: a.classId, subjectId: a.subjectId, date, period } }).then(r => { setReg(r.data); setStatuses(Object.fromEntries(r.data.students.map((s: any) => [s.id, r.data.session?.records.find((x: any) => x.studentId === s.id)?.status || 'PRESENT']))); });
useEffect(() => { load(); }, [selected, date, period]);
const submit = async () => { await api.post('/attendance/submit', { classId: a.classId, subjectId: a.subjectId, date, period, records: reg.students.map((s: any) => ({ studentId: s.id, status: statuses[s.id] })) }); setMsg('Attendance submitted and locked successfully.'); load(); }; return <div className="portal-content"><div className="page-title"><div><p>ATTENDANCE REGISTER</p><h1>Mark attendance</h1></div><button className="outline" onClick={() => setStatuses(Object.fromEntries(reg.students.map((s: any) => [s.id, 'PRESENT'])))}><Check /> Mark all present</button></div><div className="filters"><label>Class & subject<select value={selected} onChange={e => setSelected(e.target.value)}>{assign.map(x => <option value={x.id}>{x.class.name} — {x.class.section} · {x.subject.name}</option>)}</select></label><label>Date<input type="date" value={date} max={new Date().toISOString().slice(0, 10)} onChange={e => setDate(e.target.value)}/></label><label>Period<select value={period} onChange={e => setPeriod(+e.target.value)}>{[1, 2, 3, 4, 5, 6, 7, 8].map(x => <option>{x}</option>)}</select></label></div>{reg && <div className="register"><div className="register-head"><span>{reg.students.length} students</span><span>{reg.session?.state === 'SUBMITTED' ? '🔒 Submitted register' : 'Draft register'}</span></div>{reg.students.map((s: any) => <div className="student-row"><span className="roll">{String(s.rollNo).padStart(2, '0')}</span><div className="mini-avatar">{s.user.name[0]}</div><b>{s.user.name}</b><div className="segmented">{['PRESENT', 'ABSENT', 'LEAVE'].map(v => <button className={statuses[s.id] === v ? v.toLowerCase() : ''} disabled={reg.session?.state === 'SUBMITTED'} onClick={() => setStatuses({ ...statuses, [s.id]: v })}>{v[0]}<span>{v.slice(1).toLowerCase()}</span></button>)}</div></div>)}<div className="submit-row"><span>{Object.values(statuses).filter(x => x === 'PRESENT').length} present · {Object.values(statuses).filter(x => x === 'ABSENT').length} absent · {Object.values(statuses).filter(x => x === 'LEAVE').length} leave</span><button className="primary" disabled={reg.session?.state === 'SUBMITTED'} onClick={submit}>Submit attendance <ChevronRight /></button></div>{msg && <p className="success notice-success">{msg}</p>}</div>}</div>; }
function StudentAttendance() { const [data, setData] = useState<any>(); useEffect(() => { api.get('/attendance/my-report').then(r => setData(r.data)); }, []); return <div className="portal-content"><div className="page-title"><div><p>MY RECORD</p><h1>Attendance</h1></div></div><div className="attendance-score"><div style={{ '--score': `${data?.summary.percentage || 0}%` } as any}><b>{data?.summary.percentage || 0}%</b><span>This month</span></div><section>{[['Present', data?.summary.present, 'green'], ['Absent', data?.summary.absent, 'red'], ['Leave', data?.summary.leave, 'amber'], ['Total periods', data?.summary.total, 'blue']].map(x => <article><i className={String(x[2])}/><span>{x[0]}</span><b>{x[1] ?? 0}</b></article>)}</section></div><div className="table-card"><h2>Day-wise record</h2><table><thead><tr><th>Date</th><th>Subject</th><th>Period</th><th>Status</th></tr></thead><tbody>{data?.records.map((x: any) => <tr><td>{new Date(x.session.date).toLocaleDateString('en-IN')}</td><td>{x.session.subject.name}</td><td>{x.session.period}</td><td><span className={`badge ${x.status.toLowerCase()}`}>{x.status}</span></td></tr>)}</tbody></table></div></div>; }
function AdminAttendance() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { api.get('/attendance/reports').then(r => setRows(r.data)); }, []); return <div className="portal-content"><div className="page-title"><div><p>SCHOOL REPORT</p><h1>Attendance overview</h1></div></div><Table cols={['Student', 'Class', 'Roll no.', 'Present', 'Total', 'Attendance %']} rows={rows.map(x => [x.name, x.class, x.rollNo, x.present, x.total, `${x.percentage}%`])}/></div>; }
function TransferCertificate(){const{user}=useAuth();return user.role==='TEACHER'?<TeacherTC/>:<StudentTC/>}

function TeacherTC(){
    const[classes,setClasses]=useState<any[]>([]),[classId,setClassId]=useState(''),[studentId,setStudentId]=useState(''),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[uploading,setUploading]=useState(false);
    const load=()=>api.get('/portal/tc/teacher/students').then(r=>{setClasses(r.data);if(!classId&&r.data[0])setClassId(r.data[0].id)});
    useEffect(()=>{load()},[]);
    const selectedClass=classes.find(x=>x.id===classId);const students=selectedClass?.students||[];
    useEffect(()=>{setStudentId(students[0]?.id||'')},[classId,classes.length]);
    const upload=async()=>{setMessage('');setError('');if(!file||!studentId)return setError('Please select a student and PDF file.');if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return setError('Only PDF files are allowed.');if(file.size>5*1024*1024)return setError('PDF must be 5 MB or smaller.');setUploading(true);try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});await api.post('/portal/tc',{studentId,fileName:file.name,data});setMessage('TC uploaded successfully. Only the selected student can access it.');setFile(null);await load()}catch(e:any){setError(e.response?.data?.message||'TC upload failed.')}finally{setUploading(false)}};
    return <div className="portal-content"><div className="page-title"><div><p>TRANSFER CERTIFICATE</p><h1>Upload student TC</h1></div></div><div className="tc-layout"><section className="tc-upload-card"><div className="tc-icon"><Upload/></div><h2>Assign a TC PDF</h2><p>Select one of your assigned classes and the particular student. The document will remain private to that student's account.</p><label>Assigned class<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Select class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name} — Section {x.section}</option>)}</select></label><label>Student<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Select student</option>{students.map((s:any)=><option key={s.id} value={s.id}>Roll {s.rollNo} · {s.user.name}{s.transferCertificate?' · TC uploaded':''}</option>)}</select></label><label className="file-picker"><FileText/><span>{file?file.name:'Choose TC PDF (maximum 5 MB)'}</span><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary wide" disabled={uploading||!studentId||!file} onClick={upload}>{uploading?'Uploading…':'Upload TC PDF'}</button>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</section><section className="tc-roster"><h2>Class roster</h2><p>{students.length} students in selected class</p>{students.map((s:any)=><div className="tc-student" key={s.id}><span className="roll">{String(s.rollNo).padStart(2,'0')}</span><div className="mini-avatar">{s.user.name[0]}</div><b>{s.user.name}</b><span className={s.transferCertificate?'tc-ready':'tc-pending'}>{s.transferCertificate?'TC uploaded':'Not uploaded'}</span></div>)}</section></div></div>
}

function StudentTC(){
    const[certificate,setCertificate]=useState<any>(undefined),[error,setError]=useState('');useEffect(()=>{api.get('/portal/tc/me').then(r=>setCertificate(r.data)).catch(()=>setError('Unable to load your TC.'))},[]);
    const download=async()=>{try{const response=await api.get(`/portal/tc/${certificate.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=certificate.fileName;anchor.click();URL.revokeObjectURL(url)}catch{setError('Unable to download your TC.')}};
    return <div className="portal-content"><div className="page-title"><div><p>MY DOCUMENTS</p><h1>Transfer certificate</h1></div></div>{certificate===undefined?<div className="empty-card"><FileText/><div><b>Checking for your TC…</b></div></div>:certificate?<div className="student-tc-card"><div className="tc-icon"><FileText/></div><div><span>TRANSFER CERTIFICATE · PDF</span><h2>{certificate.fileName}</h2><p>Uploaded on {new Date(certificate.uploadedAt).toLocaleDateString('en-IN')} · {(certificate.fileSize/1024).toFixed(0)} KB</p></div><button className="primary" onClick={download}><Download/> Download PDF</button></div>:<div className="empty-card"><FileText/><div><b>Your TC has not been uploaded yet</b><p>It will appear here when an assigned teacher uploads it for your account.</p></div></div>}{error&&<p className="error">{error}</p>}</div>
}

function DataPage({ type }: {
    type: string;
}) { const [data, setData] = useState<any[]>([]); useEffect(() => { api.get(`/portal/${type}`).then(r => setData(r.data)); }, [type]); const title = { marks: 'Marks & results', timetable: 'Weekly timetable', notices: 'Notices & circulars' }[type]; let rows: any = [], cols: any = []; if (type === 'marks') {
    cols = ['Student', 'Subject', 'Exam', 'Score'];
    rows = data.map(x => [x.student?.user?.name || 'You', x.subject.name, x.exam, `${x.score} / ${x.maximum}`]);
} if (type === 'timetable') {
    cols = ['Day', 'Period', 'Time', 'Class', 'Subject', 'Teacher'];
    rows = data.map(x => [['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][x.dayOfWeek - 1], x.period, `${x.startsAt}–${x.endsAt}`, `${x.class.name} ${x.class.section}`, x.subject.name, x.teacher.user.name]);
} if (type === 'notices') {
    cols = ['Date', 'Title', 'Message', 'Posted by'];
    rows = data.map(x => [new Date(x.createdAt).toLocaleDateString('en-IN'), x.title, x.body, x.author.name]);
} return <div className="portal-content"><div className="page-title"><div><p>ACADEMICS</p><h1>{title}</h1></div></div><Table cols={cols} rows={rows}/></div>; }
function Table({ cols, rows }: {
    cols: string[];
    rows: any[][];
}) { return <div className="table-card"><table><thead><tr>{cols.map(x => <th>{x}</th>)}</tr></thead><tbody>{rows.length ? rows.map(r => <tr>{r.map(x => <td>{x}</td>)}</tr>) : <tr><td colSpan={cols.length} className="empty">No records yet</td></tr>}</tbody></table></div>; }
function AdminPeople() { const [t, setT] = useState<any[]>([]), [s, setS] = useState<any[]>([]); useEffect(() => { Promise.all([api.get('/admin/teachers'), api.get('/admin/students')]).then(([a, b]) => { setT(a.data); setS(b.data); }); }, []); return <div className="portal-content"><div className="page-title"><div><p>DIRECTORY</p><h1>Teachers & students</h1></div><button className="primary">+ Add person</button></div><h2 className="section-title">Teachers</h2><Table cols={['Employee no.', 'Name', 'Email', 'Qualification']} rows={t.map(x => [x.employeeNo, x.user.name, x.user.email, x.qualification])}/><h2 className="section-title">Students</h2><Table cols={['Admission no.', 'Name', 'Class', 'Roll no.', 'Parent contact']} rows={s.map(x => [x.admissionNo, x.user.name, `${x.class.name} ${x.class.section}`, x.rollNo, x.parentContact])}/></div>; }
function Academics() { return <div className="portal-content"><div className="page-title"><div><p>CONFIGURATION</p><h1>Academic structure</h1></div><button className="primary">+ Add record</button></div><div className="metric-grid"><article><span>Academic year</span><b>2026–27</b><small>Active</small></article><article><span>Manage</span><b>Classes</b><small>Sections & capacity</small></article><article><span>Manage</span><b>Subjects</b><small>Curriculum</small></article><article><span>Manage</span><b>Assignments</b><small>Teachers & classes</small></article></div></div>; }
