import{useState}from'react';import{ArrowRight,ArrowUpRight,BookOpen,Bus,Clock3,FileText,FlaskConical,GraduationCap,Mail,Menu,Send,ShieldCheck,Trophy,X}from'lucide-react';import{Link,Route,Routes}from'react-router-dom';import{api}from'../api';
const nav=[['Home','/'],['About Us','/about'],['Facilities','/facilities'],['Gallery','/gallery'],['Admissions','/admissions'],['CBSE','/cbse'],['Contact','/contact']];
function Header(){const[open,setOpen]=useState(false);return <><div className="topbar"><span>Admissions open for 2026–27</span><span><Clock3 size={14}/> Monday–Saturday · 9:00 AM–3:00 PM &nbsp; <Mail size={14}/><a href="mailto:drlokmandaspublicschool01@gmail.com">drlokmandaspublicschool01@gmail.com</a></span></div><header><Link className="brand" to="/"><span className="crest"><BookOpen/></span><span><b>Dr. Lokmandas</b><small>PUBLIC SCHOOL</small></span></Link><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([n,p])=><Link key={p} to={p} onClick={()=>setOpen(false)}>{n}</Link>)}<Link className="login-btn" to="/login">ERP Login <ArrowRight size={16}/></Link></nav></header></>}
function Footer(){return <footer><div className="brand light"><span className="crest"><BookOpen/></span><span><b>Dr. Lokmandas</b><small>PUBLIC SCHOOL</small></span></div><p>Learning with purpose. Leading with character.</p><div className="footer-contact"><span>Monday–Saturday · 9:00 AM–3:00 PM</span><a href="mailto:drlokmandaspublicschool01@gmail.com">drlokmandaspublicschool01@gmail.com</a><small>© 2026 Dr. Lokmandas Public School</small></div></footer>}
const Page=({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode})=><main><section className="page-hero"><p>{kicker}</p><h1>{title}</h1></section>{children}</main>;
function Home(){return <main><section className="hero"><video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster="/school-hero.png" aria-hidden="true"><source src="/school-hero-video.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="hero-glow" aria-hidden="true"/><div className="hero-copy"><span className="eyebrow">WELCOME TO EXCELLENCE</span><h1>Where curiosity<br/><em>becomes character.</em></h1><p>A joyful learning community where every child is known, challenged, and inspired to make a difference.</p><div className="hero-actions"><Link className="primary" to="/admissions">Begin your journey <ArrowRight/></Link><Link className="text-link" to="/about">Discover our story <ArrowRight size={16}/></Link></div></div><span className="hero-scroll" aria-hidden="true"><i/>Explore our school</span></section><section className="stats"><div><b>25+</b><span>Years of excellence</span></div><div><b>1,200</b><span>Thriving students</span></div><div><b>75+</b><span>Expert educators</span></div><div><b>18:1</b><span>Student–teacher ratio</span></div></section><section className="intro"><div><span className="eyebrow">OUR PURPOSE</span><h2>Education that reaches<br/>beyond the classroom.</h2></div><div><p>We nurture capable, compassionate learners through academic rigour, creative exploration, and a deeply rooted culture of respect.</p><Link className="text-link" to="/about">Meet our school <ArrowRight size={16}/></Link></div></section><section className="pillars"><article><GraduationCap/><h3>Academic distinction</h3><p>Thoughtful teaching and strong foundations that prepare every learner for what comes next.</p></article><article><ShieldCheck/><h3>Character & wellbeing</h3><p>A safe, inclusive environment grounded in kindness, integrity, and personal responsibility.</p></article><article><Trophy/><h3>Whole-child growth</h3><p>Sport, arts, leadership, and service help students discover who they can become.</p></article></section><section className="quote"><p>OUR VISION</p><blockquote>“To awaken the joy of learning and empower young people to lead lives of purpose.”</blockquote></section></main>}
function About(){return <Page kicker="OUR STORY" title="Rooted in values. Ready for tomorrow."><section className="content-grid"><div><h2>A school built around the learner</h2><p>For more than two decades, Dr. Lokmandas Public School has brought together ambitious academics and genuine care. Our classrooms reward questions, our community celebrates difference, and our educators see the promise in every child.</p></div><div className="card"><h3>Our mission</h3><p>To develop knowledgeable, confident, and compassionate individuals through engaging learning, ethical leadership, and meaningful community participation.</p><h3>Our values</h3><p>Curiosity · Integrity · Courage · Empathy · Excellence</p></div></section></Page>}
function Facilities(){const x=[[FlaskConical,'Science & innovation labs'],[BookOpen,'Library & learning commons'],[Trophy,'Sports complex'],[Bus,'Safe transport network']];return <Page kicker="OUR CAMPUS" title="Space to discover and grow."><section className="facility-grid">{x.map(([I,t]:any)=><article><I/><h3>{t}</h3><p>Purpose-built spaces, modern resources, and attentive supervision make learning active and safe.</p></article>)}</section></Page>}
function Gallery(){const photos=[['/gallery-campus-front.png','Our school campus'],['/gallery-food-festival.png','Foodie Fantasy — Food Village'],['/gallery-campus-court.png','Campus courtyard and activity grounds']];return <Page kicker="SCHOOL LIFE" title="Moments that shape a childhood."><section className="gallery gallery-photos">{photos.map(([src,caption],i)=><figure key={src} className={`gallery-${i+1}`}><img src={src} alt={caption} loading="lazy"/><figcaption>{caption}</figcaption></figure>)}</section></Page>}
const cbseSections=[
  {title:'Affiliation & Mandatory Disclosure',documents:[
    ['Mandatory Public Disclosure','Official CBSE Appendix IX disclosure','mandatory-public-disclosure.pdf'],
    ['Affiliation Extension Letter','CBSE extension of general affiliation','affiliation-extension-letter.pdf'],
    ['Initial Affiliation / Upgradation Letter','CBSE senior secondary upgradation record','initial-affiliation-letter.pdf'],
    ['Self-Certification Proforma','School self-certification submitted for CBSE','self-certification-proforma.pdf'],
    ['No Objection Certificate','School NOC document','noc.pdf'],
    ['Land Certificate','Certified school land document','land-certificate.pdf'],
  ]},
  {title:'Safety Certificates',documents:[
    ['Safe Drinking Water & Sanitary Certificate','Hygiene, sanitation, and drinking water certification','sanitary-certificate.pdf'],
    ['Building Safety Certificate','Building and establishment safety record','building-safety-certificate.pdf'],
    ['Fire Safety Certificate','Fire safety compliance certificate','fire-safety-certificate.pdf'],
  ]},
  {title:'Academics & School Information',documents:[
    ['Academic Calendar 2026','School events, assessments, and holidays','academic-calendar-2026.pdf'],
    ['Fee Structure 2026-27','Admission, monthly, special, and transport fees','fee-structure-2026-27.pdf'],
    ['Previous Three Years Results','Class X and XII result summary','previous-three-years-results.pdf'],
    ['Area & Classroom Statement','Campus area and infrastructure details','area-and-classrooms.pdf'],
    ['Staff Salary Statement','School staff salary statement','staff-salary-statement.pdf'],
  ]},
  {title:'Committees & Associations',documents:[
    ['School Management Committee','Committee member information','school-management-committee.pdf'],
    ['Parent-Teacher Association','Parent and teacher association members','parent-teacher-association.pdf'],
  ]},
];
function CBSE(){return <Page kicker="PUBLIC DISCLOSURE" title="CBSE information & documents."><section className="cbse-page"><div className="cbse-intro"><div><span>CBSE AFFILIATION</span><h2>Transparent. Accessible. Up to date.</h2><p>Official school documents are available below for public viewing in PDF format.</p></div><dl><div><dt>Affiliation no.</dt><dd>2131433</dd></div><div><dt>School code</dt><dd>60638</dd></div><div><dt>Documents</dt><dd>16 PDFs</dd></div></dl></div>{cbseSections.map(section=><section className="cbse-section" key={section.title}><div className="cbse-section-title"><span></span><h2>{section.title}</h2><small>{section.documents.length} documents</small></div><div className="cbse-grid">{section.documents.map(([title,description,file])=><a className="cbse-document" href={`/cbse/${file}`} target="_blank" rel="noreferrer" key={file}><span className="cbse-file-icon"><FileText/></span><span><b>{title}</b><small>{description}</small><em>PDF document</em></span><ArrowUpRight/></a>)}</div></section>)}</section></Page>}
function FormPage({contact=false}:{contact?:boolean}){const[done,setDone]=useState(false);const submit=async(e:any)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await api.post(contact?'/public/contact':'/public/admission',data);setDone(true);e.currentTarget.reset()};return <Page kicker={contact?'COME SAY HELLO':'ADMISSIONS'} title={contact?'We would love to hear from you.':'Your child’s journey starts here.'}><section className="form-layout"><div><h2>{contact?'Let’s connect':'Admission enquiry'}</h2><p>{contact?'Our school office is available during the opening hours below. You can also email us directly.':'Tell us a little about your family and our admissions team will get in touch within two working days.'}</p>{contact&&<div className="contact-list"><div className="contact-detail"><Clock3/><span><small>OPENING HOURS</small><b>Monday to Saturday</b><em>9:00 AM–3:00 PM</em></span></div><a className="contact-detail" href="mailto:drlokmandaspublicschool01@gmail.com"><Mail/><span><small>EMAIL US</small><b>drlokmandaspublicschool01@gmail.com</b><em>Click to compose an email</em></span></a></div>}</div><form onSubmit={submit}>{contact?<><label>Your name<input name="name" required/></label><label>Email<input type="email" name="email" required/></label><label>Phone<input name="phone"/></label><label>Subject<input name="subject" required/></label></>:<><label>Student name<input name="studentName" required/></label><label>Parent / guardian name<input name="parentName" required/></label><label>Email<input type="email" name="email" required/></label><label>Phone<input name="phone" required/></label><label>Grade applying for<select name="grade" required><option value="">Select grade</option>{Array.from({length:12},(_,i)=><option>Class {i+1}</option>)}</select></label></>}<label className="full">Message<textarea name="message" rows={4}/></label><button className="primary">Send enquiry <Send size={17}/></button>{done&&<p className="success">Thank you — your message has been received.</p>}</form></section></Page>}
export default function PublicSite(){return <><Header/><Routes><Route index element={<Home/>}/><Route path="about" element={<About/>}/><Route path="facilities" element={<Facilities/>}/><Route path="gallery" element={<Gallery/>}/><Route path="admissions" element={<FormPage/>}/><Route path="cbse" element={<CBSE/>}/><Route path="contact" element={<FormPage contact/>}/></Routes><Footer/></>}
